/* This file was generated by SableCC (http://www.sablecc.org/). */

package CSPMparser.analysis;

import java.util.*;
import CSPMparser.node.*;

public class IncludeFile extends AnalysisAdapter
{
	public String newfile = "";
	
    @Override
    public void caseAIncludeFile(AIncludeFile node)
    {
        inAIncludeFile(node);
        if(node.getInclude() != null)
        {
            node.getInclude().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
			System.out.println(node.getString().toString());
        }
        outAIncludeFile(node);
    }
}
