/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ivo' at '6/23/16 4:26 PM' with Gradle 2.10
 *
 * @author ivo, @date 6/23/16 4:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
